# Setup
title:        프로그램 쉽게하기
tagline:      첫번째. 나는 게을러 지기 위해 노력한다...
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       dkrend
  url:        http://dkrend.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
highlighter: rouge
encoding:     "utf-8"

future: true
